### ISSUE TITLE
Group reply as well

### ISSUE THREAD

**Issue by suntong** [shingrus/morningbtcbot#3]
Hi @shingrus, 

Could you add a logic that, when the `/update` request is sent from within the group, reply publicly to the group instead of replying privately? I think that's a strategy that benefits all parties. 

Pls consider. thx.

**Comment by shingrus** [comment]
will do if it's possible from telegram side.

**Comment by suntong** [comment]
yep, it does, 

ref:

https://github.com/suntong/nodecl/blob/88b82763cde1879d170bf88bffe2f3de5ace5178/slimbot1/sendFile2.js#L26

I.e., just reply to `message.chat.id`

**Comment by suntong** [comment]
updated OP:

> when the **`/update`** request,

**Comment by suntong** [comment]
Here is what telegram send in raw jason:

```json
{
  "update_id": 734438612,
  "message": {
    "message_id": 3,
    "from": {
      "id": 108424991,
      "first_name": "Amir",
      "last_name": "Khatibzadeh",
      "username": "AmirKht"
    },
    "chat": {
      "id": -164109857,
      "title": "AppsOnMonitoring",
      "type": "group"
    },
    "date": 1471844464,
    "text": "\/a",
    "entities": [
      {
        "type": "bot_command",
        "offset": 0,
        "length": 2
      }
    ]
  }
}
```

ref: https://github.com/amir-khatibzadeh/telegram/blob/master/TelegramWebHook/j.json
and https://github.com/col/telegram/blob/master/test/data/bot_message.json @ https://github.com/col/telegram/tree/master/test/data
and https://github.com/zammad/zammad/tree/develop/test/fixtures/telegram

**Comment by shingrus** [comment]
i've alredy implimendet that for the "update" command. but for daily subsription it will take couple days. working on...

**Comment by suntong** [comment]
Group reply works like a charm. 

Making it works for daily subscription would be super. Good for Group as well? 

THX!

**Comment by shingrus** [comment]
well, i've installed new version. 
now it sends daily updates to groups,
unfortunately you need to subscribe group or chat again
you could send /subscribe or /start from any chat
